resources:
  - name: git-resource
    type: GitRepo
    configuration:
      path: lidorv/yarden2
      gitProvider: VCS_2
      buildOn:
        pullRequestCreate: true
      branches:
        include: master
  - name: build-info-resource
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory_2
      buildName: BUILD-A
      buildNumber: $run_number
pipelines:
  - name: Pipeline-1
    configuration:
      environmentVariables:
        readOnly:
          CI: "true"
          JFROG_CLI_BUILD_NAME: BUILD-A
          JFROG_CLI_BUILD_NUMBER: $run_number
          JFROG_CLI_BUILD_URL: $step_url
    steps:
      - name: Build
        type: GoBuild
        configuration:
          resolverRepo: bbb
          goCommand: build
          environmentVariables:
            JFROG_BUILD_STATUS: PASS
          integrations:
            - name: Artifactory_2
          inputResources:
            - name: git-resource
        execution:
          onFailure:
            - export JFROG_BUILD_STATUS=FAIL
            - jfrog rt bce
            - jfrog rt bag
            - jfrog rt bp
      - name: PublishBuildInfoStep
        type: PublishBuildInfo
        configuration:
          inputResources:
            - name: git-resource
          outputResources:
            - name: build-info-resource
          inputSteps:
            - name: Build
          forceXrayScan: true
        execution:
          onComplete:
            - update_commit_status git-resource
